//Prueba de github

POST http://localhost:9000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "proyecto3",
    "email": "proyectos3utad@gmail.com",
    "activo": true,
    "password": "333",
    "role": "alumno"
}

###

GET http://localhost:9000/api/users

###
POST http://localhost:9000/api/clases HTTP/1.1
Content-Type: application/json

{
    "name": "hacking",
    "grupo": "A",
    "grado": "inso",
    "curso": "3",
    "tipoTitulacion": "grado",
    "aula": {
        "edificio": "madrid",
        "numAula": "203"
    }
}
###


POST http://localhost:3000/api/login
Content-Type: application/json
Authorization: Barear 

{
    "email": "test@test.com",
    "password": "test123"
}

###

GET http://localhost:9000/api/clases HTTP/1.1

###
POST http://localhost:9000/api/actividades HTTP/1.1
Content-Type: application/json

{
    "idCreador": "65f1862b504e9b9381e7488e",
    "asunto": "ver que no se superpongan pt5",
    "objetivo": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    "tipoActividad": "coordinacion",
    "ambitoTitulacion": "3",
    "documentoDescriptivo": "grado",
    "asistentesRequeridos": ["65f1862b504e9b9381e7488e"],
    "espacio": {
        "tipo": "virtual"
    },
    "fecha": "2024-03-13T13:00:29.717Z",
    "hora": "2024-03-13T13:00:29.717Z"
}
###
GET http://localhost:9000/api/foro HTTP/1.1
###

POST http://localhost:9000/api/foro HTTP/1.1
Content-Type: application/json

{
    "name": "el sisas",
    "descripcion": "por q en la carcel hay mucha droga",
    "mensaje": [{
        "idUsuario": ["65f18b2b21498baad40d0085"],
        "titulo": "Mensaje añadido 2",
        "texto": "PA TOA LAS REKETONAS, Q LES VOY A PARTI TOAS LAS BRAGAS",
        "etiquetas": ["churumbereketon", "churumbegitanofino0"]
    }]
}
###
POST http://localhost:9000/api/foro/660eeb66f708c083e7556e4c/mensaje HTTP/1.1
Content-Type: application/json

{
    "mensaje": {
        "idUsuario": ["65f18b2b21498baad40d0085"],
        "titulo": "Mensaje añadido 5",
        "texto": "PA TOA LAS REKETONAS, Q LES VOY A PARTI LOS HUESOS COMO UNA GAMBA",
        "etiquetas": ["churumbereketon", "churumbegitanofino0"]
    }
}

# OBTENER MENSAJES DE UN FORO CON UN ID CONCRETO
###
GET http://localhost:9000/api/foro/660eeb66f708c083e7556e4c/mensajes HTTP/1.1

###
POST http://localhost:9000/api/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="img.png"
Content-Type: image/png

< ./img.png
--Boundry--
###

POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "proyecto3",
    "email": "proyectos3utad@gmail.com",
    "activo": true,
    "password": "333",
    "rol": "alumno"
}

###

PUT http://localhost:9000/api/users/proyectos3utad@gmail.com HTTP/1.1
Content-Type: application/json

{
    "password": "333" 
}

###

GET http://localhost:9000/api/users HTTP/1.1

###

GET http://localhost:9000/api/users/65d895228b0c4d2f0b340030 HTTP/1.1

###

POST http://localhost:9000/api/tracks HTTP/1.1
Content-Type: application/json

{
    "dato": "basura",
    "name": "Ric",
    "album": "Album",
    "cover": "http://mmmm.com",
    "artist": {
        "name": "Bas",
        "nickname": "rsurname",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0123456789abcdef01234567"
  
}

###

POST http://localhost:9000/api/tracks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYwMTE5ZjVkM2MxZWFkZTJkMjFhMzEiLCJlbWFpbCI6InRlc3RlbzJAZ21haWwuY29tIiwiaWF0IjoxNzEwMjMxOTY3LCJleHAiOjE3MTAyMzkxNjd9.er1r9k0bilGiuaOcJrDvItNpJSRewhFePapif4Lf2-8

{
    "dato": "iueskflitgsdrziugfb",
    "name": "oñixzfivlzs",
    "album": "piñdzxuyfgb",
    "cover": "http://ñizxurgfzs.com",
    "artist": {
        "name": "ñlkzxighn",
        "nickname": "oisdybñ",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "23456789abcdef0123456789"
  
}

###

PUT http://localhost:9000/api/tracks/65d46354fadd263f55799d68 HTTP/1.1
Content-Type: application/json


{
    "name": "AlbaClase",
    "album": "Disco",
    "cover": "http://pruebaPOST2.com",
    "artist": {
        "name": "BasuraXdd",
        "nickname": "rsurname",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":5
    },
    "mediaId": "0123456789abcdef01234567"
  
}

###

DELETE http://localhost:9000/api/tracks/65d464d87ceb92d939c7788d

###
#soft delete
DELETE http://localhost:9000/api/tracks/65e1d446db624ab6e04c2f68

###
POST  http://localhost:9000/api/auth/register HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYwMTE5ZjVkM2MxZWFkZTJkMjFhMzEiLCJlbWFpbCI6InRlc3RlbzJAZ21haWwuY29tIiwiaWF0IjoxNzEwMjMxOTY3LCJleHAiOjE3MTAyMzkxNjd9.er1r9k0bilGiuaOcJrDvItNpJSRewhFePapif4Lf2-8
api_key: Api-publica-123

{
    "name": "testeo3",
    "age": "40",
    "email": "testeo2@gmail.com",
    "password": "testeo22222"
  
}

###

GET http://localhost:9000/api/tracks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYwMTE5ZjVkM2MxZWFkZTJkMjFhMzEiLCJlbWFpbCI6InRlc3RlbzJAZ21haWwuY29tIiwiaWF0IjoxNzEwMjMxOTY3LCJleHAiOjE3MTAyMzkxNjd9.er1r9k0bilGiuaOcJrDvItNpJSRewhFePapif4Lf2-8



