# PETICIONES USUARIOS
# Todas las peticiones necesitan token JWT
# Se ha probado todas las peticiones desde el back-end y todas funcionan.

# REGISTRO DE USUARIO (FUNCIONA CON TOKEN JWT)
POST  http://localhost:9000/api/auth/register HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "name": "andres perez",
    "email": "andresperez@gmail.com",
    "age": "40",
    "activo": true,
    "password": "123",
    "role": "admin"
}
###

# LOGGIN USUARIO (FUNCIONA CPON TOKEN JWT)
POST http://localhost:9000/api/auth
Content-Type: application/json

{
    "email": "andresperez@gmail.com",
    "password": "123"
}
###

# CAMBIAR CONTRASEÑA USUARIO CON ID ESPECÍFICO Y SE ALMACENA ENCRIPTADA EN LA BBDD (FUNCIONA CON TOKEN JWT)
PUT http://localhost:9000/api/users/6638fae63d5c49f012c853d6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjM4ZmFlNjNkNWM0OWYwMTJjODUzZDYiLCJlbWFpbCI6ImFuZHJlc3BlcmV6QGdtYWlsLmNvbSIsImlhdCI6MTcxNTAxMDQ1NiwiZXhwIjoxNzE1MDE3NjU2fQ.UMq7kDZpl_BULTNhdhMXaxN5BB2W-82LNYLnmobndrg

{
    "password": "qwerty" 
}
###

# OBTENER TODOS LOS USUARIOS (FUNCIONA CON TOKEN JWT)
GET http://localhost:9000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjM4ZmFlNjNkNWM0OWYwMTJjODUzZDYiLCJlbWFpbCI6ImFuZHJlc3BlcmV6QGdtYWlsLmNvbSIsImlhdCI6MTcxNTAxMDQ1NiwiZXhwIjoxNzE1MDE3NjU2fQ.UMq7kDZpl_BULTNhdhMXaxN5BB2W-82LNYLnmobndrg
###

# OBTENER USUARIO CON ID CONCRETO (FUNCIONA CON TOKEN JWT)
GET http://localhost:9000/api/users/6638fae63d5c49f012c853d6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjM4ZmFlNjNkNWM0OWYwMTJjODUzZDYiLCJlbWFpbCI6ImFuZHJlc3BlcmV6QGdtYWlsLmNvbSIsImlhdCI6MTcxNTAxMDQ1NiwiZXhwIjoxNzE1MDE3NjU2fQ.UMq7kDZpl_BULTNhdhMXaxN5BB2W-82LNYLnmobndrg
###

# AÑADIR ACTIVIDAD A PERFIL DE USUARIO (FUNCIONA CON TOKEN JWT)
PATCH http://localhost:9000/api/actividades/6618ea582321f5c76c1ea2d7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjM4ZmFlNjNkNWM0OWYwMTJjODUzZDYiLCJlbWFpbCI6ImFuZHJlc3BlcmV6QGdtYWlsLmNvbSIsImlhdCI6MTcxNTAxMDQ1NiwiZXhwIjoxNzE1MDE3NjU2fQ.UMq7kDZpl_BULTNhdhMXaxN5BB2W-82LNYLnmobndrg
Content-Type: application/json

{
    "id": "6638fae63d5c49f012c853d6"
}
###